FROM apache/airflow:3.3.1-python3.12

ARG AIRFLOW_VERSION=3.3.1

COPY --chown=airflow:root pyproject.toml README.md /opt/airflow/project/
COPY --chown=airflow:root src /opt/airflow/project/src

RUN pip install --no-cache-dir \
    "apache-airflow==${AIRFLOW_VERSION}" \
    /opt/airflow/project
